name: 测试调用 self-hosted reusable

on:
  workflow_dispatch:

jobs:
  test-selfhosted:
    uses: ./.github/workflows/test-release-selfhosted.yaml
    with:
      device-id: shiba
      magisk-preinit-device: sda10
    secrets: inherit
