name: 测试B - 用 github.event.inputs

on:
  workflow_call:
    inputs:
      device-id:
        type: string
  workflow_dispatch:
    inputs:
      device-id:
        description: Device
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "device=${{ github.event.inputs.device-id || inputs.device-id || 'shiba' }}"
