name: 测试调用 nopush reusable

on:
  workflow_dispatch:

jobs:
  test-nopush:
    uses: ./.github/workflows/test-release-nopush.yaml
    with:
      device-id: shiba
      magisk-preinit-device: sda10
    secrets: inherit
