name: 测试A - 只用 inputs.xxx

on:
  workflow_call:
    inputs:
      device-id:
        type: string
  workflow_dispatch:
    inputs:
      device-id:
        description: Device
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "device=${{ inputs.device-id || 'shiba' }}"
