name: 测试调用 complex-expr

on:
  workflow_dispatch:

jobs:
  test-complex:
    uses: ./.github/workflows/test-complex-expr.yaml
    with:
      device-id: shiba
      magisk-preinit-device: sda10
    secrets: inherit
