name: 测试3c - no permissions block

on:
  workflow_call:
    inputs:
      device-id:
        type: string
  workflow_dispatch:
    inputs:
      device-id:
        description: Device
        required: true

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    steps:
      - run: echo "hello ${{ runner.os }}"
