name: 测试3b - cache restore with hardcoded key

on:
  workflow_call:
    inputs:
      device-id:
        type: string
  workflow_dispatch:
    inputs:
      device-id:
        description: Device
        required: true

jobs:
  build:
    runs-on: [self-hosted, linux, x64]
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - uses: actions/cache/restore@v4
        with:
          path: .tool-cache
          key: tool-cache-v1
